window.loadSentenceData("Уровень 1: Основы", [
    { ru: "Я учу немецкий", de: "Ich lerne Deutsch", grammar: "В обычном предложении глагол (действие) всегда стоит на втором месте." },
    { ru: "Ты мой друг", de: "Du bist mein Freund", grammar: "Для 'ты' глагол 'быть' превращается в 'bist'." },
    { ru: "Мы идем в кино", de: "Wir gehen ins Kino", grammar: "'ins' — это короткий способ сказать 'в' (в кино)." },
    { ru: "Он живет в Берлине", de: "Er wohnt in Berlin", grammar: "С городами просто говорим 'in' без лишних слов." },
    { ru: "Она пьет кофе", de: "Sie trinkt Kaffee", grammar: "Для 'она' к глаголу добавляется окончание -t." },
    { ru: "Это стол", de: "Das ist ein Tisch", grammar: "Когда называем предмет, используем связку 'Das ist'." },
    { ru: "У меня есть кошка", de: "Ich habe eine Katze", grammar: "После 'имею' (habe) предмет женского рода получает артикль 'eine'." },
    { ru: "Мы играем в футбол", de: "Wir spielen Fußball", grammar: "В немецком говорят просто 'играть футбол', без слова 'в'." },
    { ru: "Она родом из России", de: "Sie kommt aus Russland", grammar: "'kommt aus' означает 'происходит из' или 'приехал из'." },
    { ru: "Я люблю музыку", de: "Ich love Musik", grammar: "Сначала кто (Я), потом действие (люблю), потом что (музыку)." },
    { ru: "Мы учим слова", de: "Wir lernen Wörter", grammar: "Слово 'Wörter' означает много слов." },
    { ru: "Ты делаешь это хорошо", de: "Du machst das gut", grammar: "Слово 'gut' (хорошо) ставится в конце фразы." },
    { ru: "Они работают здесь", de: "Sie arbeiten hier", grammar: "Для 'они' глагол остается в начальной форме (окончание -en)." },
    { ru: "Меня зовут Анна", de: "Ich heiße Anna", grammar: "Глагол 'heißen' (зваться) — базовый способ представиться." },
    { ru: "Книга интересная", de: "Das Buch ist interessant", grammar: "Описываем предмет через связку 'ist'." },
    { ru: "У меня есть брат", de: "Ich habe einen Bruder", grammar: "Для мужского рода после 'имею' артикль превращается в 'einen'." },
    { ru: "Где вокзал?", de: "Wo ist der Bahnhof", grammar: "Глагол (ist) идет сразу после вопросительного слова (Где)." },
    { ru: "Я покупаю хлеб", de: "Ich kaufe Brot", grammar: "Продукты часто называем просто так, без артиклей." },
    { ru: "Мы слушаем радио", de: "Wir hören Radio", grammar: "Глагол на втором месте." },
    { ru: "Ты пишешь письмо", de: "Du schreibst einen Brief", grammar: "Письмо (Brief) мужского рода, поэтому в этом месте пишем 'einen'." },
    { ru: "Он ищет ключи", de: "Er sucht die Schlüssel", grammar: "Для 'он' у глагола окончание -t." },
    { ru: "Она готовит суп", de: "Sie kocht eine Suppe", grammar: "Суп женского рода — используем 'eine'." },
    { ru: "Мы едем домой", de: "Wir fahren nach Hause", grammar: "'nach Hause' — это устойчивое сочетание, означающее 'домой'." },
    { ru: "Погода хорошая", de: "Das Wetter ist gut", grammar: "Погода (Wetter) — среднего рода (das)." },
    { ru: "У тебя есть время?", de: "Hast du Zeit", grammar: "В вопросе действие (глагол) выходит на самое первое место." },
    { ru: "Я живу здесь", de: "Ich wohne hier", grammar: "Я (кто) -> живу (действие) -> здесь (где)." },
    { ru: "Они играют в парке", de: "Sie spielen im Park", grammar: "'im' — это коротко 'в' (в парке)." },
    { ru: "Это моя машина", de: "Das ist mein Auto", grammar: "Машина (Auto) среднего рода, поэтому просто 'mein'." },
    { ru: "Я вижу собаку", de: "Ich sehe einen Hund", grammar: "Собака мужского рода, поэтому пишем 'einen Hund'." },
    { ru: "Ты понимаешь меня?", de: "Verstehst du mich", grammar: "Вопрос начинаем с действия (Verstehst)." },
    { ru: "Мы любим пиццу", de: "Wir lieben Pizza", grammar: "Обычный порядок слов." },
    { ru: "Он читает газету", de: "Er liest eine Zeitung", grammar: "Глагол 'читать' (lesen) меняется внутри для него: er liest." },
    { ru: "Она поет песню", de: "Sie singt ein Lied", grammar: "Песня среднего рода — используем 'ein'." },
    { ru: "Я работаю врачом", de: "Ich arbeite als Arzt", grammar: "Перед профессией ставим слово 'als' (как/в качестве)." },
    { ru: "Это дорого", de: "Das ist teuer", grammar: "Описываем ситуацию через 'Das ist'." },
    { ru: "У нас есть проблема", de: "Wir haben ein Problem", grammar: "Проблема среднего рода — используем 'ein'." },
    { ru: "Ты говоришь быстро", de: "Du sprichst schnell", grammar: "Глагол 'говорить' (sprechen) меняется для 'ты': du sprichst." },
    { ru: "Они изучают английский", de: "Sie lernen Englisch", grammar: "Названия языков пишутся без артиклей." },
    { ru: "Я сплю долго", de: "Ich schlafe lange", grammar: "Глагол на втором месте." },
    { ru: "Это вкусно", de: "Das ist lecker", grammar: "Простое описание через 'Das ist'." }
]);
