window.loadSentenceData("Уровень 4: Эксперт", [
    { ru: "Дом был построен моим дедушкой", de: "Das Haus wurde von meinem Opa gebaut", grammar: "Пассивный залог: используйте 'wurde' (был) на втором месте и само действие (построен/gebaut) в самом конце." },
    { ru: "Книга должна быть прочитана до завтра", de: "Das Buch muss bis morgen gelesen werden", grammar: "Пассив с модальным глаголом: 'muss' на втором месте, а связка 'gelesen werden' — в конце." },
    { ru: "После того как он пришел, мы начали есть", de: "Nachdem er gekommen war, fingen wir an zu essen", grammar: "После 'Nachdem' (после того как) действие 'был' (war) ставится в самый конец своей части предложения." },
    { ru: "Ей подарили красивый букет цветов", de: "Ihr wurde ein schöner Blumenstrauß gesченkt", grammar: "Пассивный залог: 'wurde' (было подарено) на втором месте." },
    { ru: "Дверь была открыта ветром", de: "Die Tür wurde vom Wind geöffnet", grammar: "Кем/чем? В пассивном залоге используем 'von' + артикль (vom)." },
    { ru: "Я спросил его, сделал ли он это", de: "Ich fragte ihn, ob er das gemacht hatte", grammar: "В вопросе 'ли' (ob) действие 'имел/сделал' (hatte) уходит в самый конец." },
    { ru: "Он сказал, что уже видел этот фильм", de: "Er sagte, dass er diesen Film schon gesehen habe", grammar: "Когда передаем чужие слова ('он сказал, что...'), глагол 'habe' ставится в конец." },
    { ru: "Машина была отремонтирована механиком", de: "Das Auto wurde vom Mechaniker repariert", grammar: "Wurde + vom (кем-то) + действие в конце." },
    { ru: "Я не знал, что ты уже ушел", de: "Ich wusste nicht, dass du schon gegangen warst", grammar: "Предпрошедшее время: действие 'был' (warst) ставится в конец после 'dass'." },
    { ru: "Задача будет решена нами", de: "Die Aufgabe wird von uns gelöst werden", grammar: "Будущее время в пассиве: 'wird' на втором месте, 'gelöst werden' — в конце." },
    { ru: "Хотя он много работал, он не устал", de: "Obwohl er viel gearbeitet hatte, war er nicht müde", grammar: "После 'Obwohl' (хотя) глагол 'hatte' в конце первой части." },
    { ru: "Письмо было отправлено вчера", de: "Der Brief wurde gestern abgeschickt", grammar: "Wurde ... abgeschickt." },
    { ru: "Меня пригласили на вечеринку", de: "Ich wurde zur Party eingeladen", grammar: "Пассив: 'был приглашен' (wurde ... eingeladen)." },
    { ru: "Я думал, что ты спишь", de: "Ich dachte, dass du schläfst", grammar: "В придаточном предложении действие (schläfst) в конце." },
    { ru: "Никто не знал, где спрятаны деньги", de: "Niemand wusste, wo das Geld versteckt war", grammar: "В косвенном вопросе (где...) глагол (war) в конце." },
    { ru: "Мост был разрушен во время войны", de: "Die Brücke wurde im Krieg zerstört", grammar: "Wurde ... zerstört." },
    { ru: "Она утверждала, что не видела его", de: "Sie behauptete, dass sie ihn nicht gesehen habe", grammar: "Передача чужих слов через 'dass' и особую форму глагола (habe) в конце." },
    { ru: "Если бы я знал это раньше, я бы не пришел", de: "Wenn ich das früher gewusst hätte, wäre ich nicht gekommen", grammar: "Сложное условие: 'Если бы' (Wenn) выгоняет 'hätte' в конец первой части." },
    { ru: "Он вел себя так, как будто ничего не случилось", de: "Er tat so, als ob nichts passiert wäre", grammar: "Как будто (als ob) — действие 'было' (wäre) в самом конце." },
    { ru: "Врач сказал, что пациенту нужно отдыхать", de: "Der Arzt sagte, что пациенту sich ausruhen müsse", grammar: "Чужая речь: 'müsse' (должен был бы) в конце." },
    { ru: "Здание было продано за миллион евро", de: "Das Gebäude wurde für eine Million Euro verkauft", grammar: "Wurde ... verkauft." },
    { ru: "Мы ждали, пока дождь прекратится", de: "Wir warteten, bis der Regen aufhörte", grammar: "После 'bis' (пока/до тех пор) действие (aufhörte) в конце." },
    { ru: "Он спросил, можно ли здесь курить", de: "Er fragte, ob man hier rauchen dürfe", grammar: "Ли (ob) — действие 'dürfe' в конце." },
    { ru: "Я был бы рад, если бы ты помог мне", de: "Ich wäre froh, wenn du mir helfen würdest", grammar: "Если бы (wenn) — вспомогательное слово 'würdest' в самом конце." },
    { ru: "Ты выглядишь так, будто увидел призрака", de: "Du siehst aus, als hättest du ein Gespenst gesehen", grammar: "Словно (als) — порядок слов меняется, как в придаточном." }
]);
