window.loadSentenceData("Уровень 2: Порядок слов", [
    { ru: "Сегодня я иду работать", de: "Heute gehe ich arbeiten", grammar: "Если предложение начинается с времени (Сегодня), то действие (иду) остается на втором месте, а 'я' уходит на третье." },
    { ru: "Завтра мы занимаемся спортом", de: "Morgen machen wir Sport", grammar: "Сначала когда (Morgen), потом действие (machen), потом кто (wir)." },
    { ru: "Я умею хорошо плавать", de: "Ich kann gut schwimmen", grammar: "Слово 'умею' (kann) на втором месте, а само действие (плавать) — в самом конце." },
    { ru: "Мы должны идти домой", de: "Wir müssen nach Hause gehen", grammar: "Должен (müssen) на втором месте, а второе действие (идти) — в самом конце." },
    { ru: "В понедельник я учу немецкий", de: "Am Montag lerne ich Deutsch", grammar: "Дни недели всегда используются с маленьким словом 'Am'." },
    { ru: "Здесь нельзя курить", de: "Hier darf man nicht rauchen", grammar: "'man darf nicht' — это способ сказать 'не разрешено'." },
    { ru: "Возможно, он придет позже", de: "Vielleicht kommt er später", grammar: "После слова 'Vielleicht' (Возможно) сразу ставим действие (придет)." },
    { ru: "Я хотел бы выпить воды", de: "Ich möchte Wasser trinken", grammar: "'Хотел бы' (möchte) на втором месте, а действие 'пить' — в конце." },
    { ru: "В выходные я долго сплю", de: "Am Wochenende schlafe ich lange", grammar: "После 'Am Wochenende' (в выходные) ставим действие (сплю)." },
    { ru: "Почему ты грустный?", de: "Warum bist du traurig", grammar: "В вопросе глагол (bist) идет сразу за вопросительным словом." },
    { ru: "Где ты живешь?", de: "Wo wohnst du", grammar: "Действие 'живешь' (wohnst) идет вторым." },
    { ru: "Что ты делаешь сейчас?", de: "Was machst du jetzt", grammar: "Сначала что (Was), потом делаешь (machst)." },
    { ru: "Я могу тебе помочь", de: "Ich kann dir helfen", grammar: "Помочь кому? Тебе — в немецком это будет 'dir'." },
    { ru: "Мы хотим купить хлеб", de: "Wir wollen Brot kaufen", grammar: "Хотим (wollen) на втором месте, купить (kaufen) — в конце." },
    { ru: "Вечером я читаю книгу", de: "Abends lese ich ein Buch", grammar: "Когда начинаем с времени (Вечером/Abends), действие (читаю) идет следом." },
    { ru: "Обычно она завтракает рано", de: "Normalerweise frühstückt sie früh", grammar: "После слова 'Обычно' (Normalerweise) сразу идет действие (завтракает)." },
    { ru: "К сожалению, у меня нет времени", de: "Leider habe ich keine Zeit", grammar: "'Leider' (К сожалению) на первом месте, действие 'имею' (habe) на втором." },
    { ru: "Ты должен это знать", de: "Du musst das wissen", grammar: "Знать (wissen) уходит в самый конец предложения." },
    { ru: "Мы можем пойти в кино", de: "Wir können ins Kino gehen", grammar: "Можем (können) — второе слово, идти (gehen) — последнее." },
    { ru: "Когда ты придешь?", de: "Wann kommst du", grammar: "Когда (Wann) -> придешь (kommst) -> ты (du)." },
    { ru: "На столе стоит лампа", de: "Auf dem Tisch steht eine Lampe", grammar: "Если говорим 'где именно' (на столе), артикль меняется на 'dem'." },
    { ru: "В школе мы учим математику", de: "In der Schule lernen wir Mathe", grammar: "Школа женского рода, но в фразе 'в школе' артикль меняется на 'der'." },
    { ru: "Летом здесь очень жарко", de: "Im Sommer ist es hier sehr heiß", grammar: "Времена года (Лето/Sommer) используются с коротким словом 'Im'." },
    { ru: "Конечно, я помогу тебе", de: "Natürlich helfe ich dir", grammar: "После 'Конечно' (Natürlich) сразу ставим действие (помогу)." },
    { ru: "Ты хочешь пойти с нами?", de: "Willst du mit uns gehen", grammar: "В вопросе без 'что/где/когда' действие всегда на первом месте." },
    { ru: "Я не должен это делать", de: "Ich darf das nicht machen", grammar: "Запрет 'нельзя' — это 'darf ... nicht'." },
    { ru: "Вчера мы были в парке", de: "Gestern waren wir im Park", grammar: "Сначала когда (Вчера), потом были (waren)." },
    { ru: "Скоро придет поезд", de: "Bald kommt der Zug", grammar: "После 'Скоро' (Bald) идет действие (придет)." },
    { ru: "Здесь живет моя бабушка", de: "Hier wohnt meine Oma", grammar: "Действие (живет) на втором месте." },
    { ru: "Почему ты смеешься?", de: "Warum lachst du", grammar: "Почему -> действие -> кто." },
    { ru: "Естественно, это важно", de: "Natürlich ist das wichtig", grammar: "Сначала 'конечно' (Natürlich), потом связка (ist)." },
    { ru: "Сначала мы поедим", de: "Zuerst essen wir", grammar: "После 'Сначала' (Zuerst) идет действие (едим)." },
    { ru: "Потом мы пойдем гулять", de: "Dann gehen wir spazieren", grammar: "После 'Потом' (Dann) идет действие (идем)." },
    { ru: "Иногда я забываю слова", de: "Manchmal vergesse ich Wörter", grammar: "Иногда (Manchmal) -> забываю (vergesse) -> я (ich)." },
    { ru: "Вероятно, будет дождь", de: "Wahrscheinlich wird es regnen", grammar: "Для будущего времени используйте вспомогательный глагол 'wird' (станет) и основное действие 'regnen' в самом конце." },
    { ru: "Ты умеешь танцевать?", de: "Kannst du tanzen", grammar: "Вопрос начинаем с умения (Kannst)." },
    { ru: "Мы хотели бы заказать пиццу", de: "Wir möchten Pizza bestellen", grammar: "Хотели бы (möchten) — второе слово, заказать — последнее." },
    { ru: "В воскресенье магазины закрыты", de: "Am Sonntag sind die Geschäfte geschlossen", grammar: "С днями недели всегда используем 'Am'." },
    { ru: "Кто этот человек?", de: "Wer ist dieser Mann", grammar: "Слово 'dieser' означает 'этот' (мужской род)." },
    { ru: "Я должен вставать рано", de: "Ich muss früh aufstehen", grammar: "У глагола 'вставать' (aufstehen) приставка 'auf' обычно отделяется, но при работе с 'должен' (muss) он остается целым в конце." }
]);
