window.loadSentenceData("Уровень 5: Мастер", [
    { ru: "Если бы у меня было много денег, я бы купил остров", de: "Wenn ich viel Geld hätte, würde ich eine Insel kaufen", grammar: "Мечты: В части с 'Если бы' (Wenn) слово 'hätte' в конце, во второй части 'würde' (бы) на первом или втором месте." },
    { ru: "Я сделал бы это по-другому на твоем месте", de: "Ich hätte das an deiner Stelle anders gemacht", grammar: "Прошлое, которое не случилось: 'hätte' (бы сделал) на втором месте, а само действие (gemacht) — в конце." },
    { ru: "Чем больше я учу, тем больше я знаю", de: "Je mehr ich lerne, desto mehr weiß ich", grammar: "Сравнение: после 'Je mehr' действие в конце (lerne), после 'desto mehr' — действие сразу (weiß)." },
    { ru: "Не только он, но и она пришла на встречу", de: "Nicht nur er, sondern auch sie kam zum Treffen", grammar: "Двойной союз: 'Не только... но и...' (Nicht nur ... sondern auch)." },
    { ru: "Либо мы идем сейчас, либо остаемся дома", de: "Entweder gehen wir jetzt oder wir bleiben zu Hause", grammar: "Выбор: 'Либо... либо...' (Entweder ... oder)." },
    { ru: "Он не только умен, но и очень добр", de: "Er ist nicht nur klug, sondern auch sehr nett", grammar: "Двойной союз 'не только... но и...'." },
    { ru: "Я бы хотел, чтобы ты был здесь", de: "Ich wünschte, du wärst hier", grammar: "Мечта: 'wärst' (был бы) ставится в конец или после подлежащего." },
    { ru: "На твоем месте я бы извинился", de: "An deiner Stelle würde ich mich entschuldigen", grammar: "Совет: 'würde' (бы) на втором месте, само действие — в конце." },
    { ru: "Нужно было сказать мне об этом раньше", de: "Du hättest mir das früher sagen sollen", grammar: "Упрек: три глагола в конце, модальный 'sollen' — последний." },
    { ru: "Если бы не дождь, мы бы пошли гулять", de: "Wenn es nicht geregnet hätte, wären wir spazieren gegangen", grammar: "Условие в прошлом: 'hätte' (было) в конце первой части, 'wären' (были бы) во второй." },
    { ru: "Он говорит по-немецки так же хорошо, как и по-английски", de: "Er spricht genauso gut Deutsch wie Englisch", grammar: "Сравнение 'так же... как': genauso ... wie." },
    { ru: "С одной стороны это дешево, с другой стороны — плохое качество", de: "Einerseits ist es billig, andererseits ist die Qualität schlecht", grammar: "Противопоставление: 'Einerseits ... andererseits'. Глагол (ist) всегда сразу после этих слов." },
    { ru: "Ни я, ни мой брат не умеем плавать", de: "Weder ich noch mein Bruder können schwimmen", grammar: "Отрицание 'Ни... ни...': Weder ... noch." },
    { ru: "Ты мог бы позвонить мне вчера!", de: "Du hättest mich gestern anrufen können", grammar: "Упрек: модальный глагол 'können' (мог бы) ставится в самый конец." },
    { ru: "Я едва успел на поезд", de: "Ich habe den Zug kaum erreicht", grammar: "Слово 'кадва' (kaum) ставится перед действием или объектом." },
    { ru: "Стоило бы купить билеты заранее", de: "Es hätte sich gelohnt, die Tickets im Voraus zu kaufen", grammar: "Сложное выражение: 'hätte sich gelohnt' (стоило бы того)." },
    { ru: "Это, безусловно, лучшее решение", de: "Das ist zweifellos die beste Entscheidung", grammar: "Безусловно — zweifellos." },
    { ru: "Как бы то ни было, мы должны решить это", de: "Wie dem auch sei, wir müssen das lösen", grammar: "Устойчивое выражение: 'Wie dem auch sei' (как бы там ни было)." },
    { ru: "Предположим, что это правда", de: "Angenommen, dass das wahr ist", grammar: "Предположим — angenommen." },
    { ru: "Вопреки ожиданиям, погода была хорошей", de: "Wider Erwarten war das Wetter schön", grammar: "Вопреки — Wider Erwarten." },
    { ru: "Вместо того чтобы работать, он смотрит телевизор", de: "Anstatt zu работать, sieht er fern", grammar: "Вместо того чтобы: 'Anstatt ... zu' + действие в конце." },
    { ru: "Без тебя я бы не справился", de: "Ohne dich hätte ich es nicht geschafft", grammar: "Мечта о прошлом: 'hätte' на втором месте, действие в конце." },
    { ru: "Это зависит от того, сколько это стоит", de: "Es kommt darauf an, wie viel es kostet", grammar: "Устойчивое выражение: 'Es kommt darauf an' (это зависит от того...)." },
    { ru: "Что касается меня, я согласен", de: "Was mich betrifft, bin ich einverstanden", grammar: "Вводная фраза 'Что касается меня' вызывает инверсию глагола (bin) во второй части." },
    { ru: "По всей вероятности, он опоздает", de: "Aller Wahrscheinlichkeit nach wird er sich verspäten", grammar: "Устойчивое выражение: 'Aller Wahrscheinlichkeit nach' (по всей вероятности)." }
]);
