window.loadSentenceData("Уровень 3: Сложные фразы", [
    { ru: "Я вчера играл в футбол", de: "Ich habe gestern Fußball gespielt", grammar: "Прошедшее время: используйте вспомогательный глагол 'habe' на втором месте и само действие с приставкой ge- (gespielt) в самом конце." },
    { ru: "Мы ездили в Германию", de: "Wir sind nach Deutschland gefahren", grammar: "Для глаголов движения (ехать/идти) в прошлом используйте 'sind' вместо 'habe'." },
    { ru: "Я помогаю моей маме каждый день", de: "Ich helфе моей маме jeden Tag", grammar: "Помогать кому? В немецком 'маме' (die Mutter) в этом случае превращается в 'meiner Mutter'." },
    { ru: "Эта машина принадлежит моему отцу", de: "Das Auto gehört meinem Vater", grammar: "Принадлежать кому? Мужской род (отец) превращается в 'meinem Vater'." },
    { ru: "Я знаю, что ты умный", de: "Ich weiß, dass du klug bist", grammar: "Когда добавляете пояснение через 'что' (dass), глагол (bist) всегда уходит в самый конец предложения." },
    { ru: "Он говорит, что он болен", de: "Er sagt, dass er krank ist", grammar: "После слова 'что' (dass) действие (ist) ставится в самый конец." },
    { ru: "Так как идет дождь, я остаюсь дома", de: "Weil es regnet, bleibe ich zu Hause", grammar: "В части предложения со словом 'потому что' (weil) действие (regnet) уходит в конец этой части." },
    { ru: "Когда у меня есть время, я прихожу", de: "Wenn ich Zeit habe, komme ich", grammar: "В части со словом 'когда/если' (wenn) действие (habe) стоит в конце." },
    { ru: "Я дарю брату книгу", de: "Ich schenke dem Bruder ein Buch", grammar: "Кому? (брату) — мужской род превращается в 'dem Bruder'." },
    { ru: "С моими друзьями я иду в парк", de: "Mit meinen Freunden gehe ich in den Park", grammar: "После слова 'С' (Mit) всегда используется множественное число с окончанием -n (Freunden)." },
    { ru: "Я не купил молока", de: "Ich habe keine Milch gekauft", grammar: "Прошедшее время: habe ... gekauft." },
    { ru: "Ты уже сделал домашнее задание?", de: "Hast du schon die Hausaufgaben gemacht?", grammar: "Вопрос в прошлом: Глагол 'Hast' на первом месте, а действие 'сделал' (gemacht) — в конце." },
    { ru: "Мы идем гулять, хотя холодно", de: "Wir gehen spazieren, obwohl es kalt ist", grammar: "После слова 'хотя' (obwohl) действие (ist) ставится в самый конец." },
    { ru: "Я думаю, что это важно", de: "Ich denke, dass das wichtig ist", grammar: "Конструкция 'что...' (dass) выгоняет глагол (ist) в конец." },
    { ru: "К сожалению, я не могу прийти", de: "Leider kann ich nicht kommen", grammar: "После 'Leider' (К сожалению) идет действие (могу/kann)." },
    { ru: "Он купил машину, которая быстрая", de: "Er hat ein Auto gekauft, das schnell ist", grammar: "Описываем предмет через 'которая' (das) — действие (ist) уходит в конец." },
    { ru: "Я рад, что ты здесь", de: "Ich bin froh, dass du hier bist", grammar: "После 'что' (dass) глагол в конце." },
    { ru: "Мы посетили музей, который старый", de: "Wir haben das Museum besucht, das alt ist", grammar: "Относительное предложение: das ... ist." },
    { ru: "Если ты хочешь, мы можем поехать", de: "Wenn du willst, können wir fahren", grammar: "После 'Если' (Wenn) действие (хочешь) в конце своей части." },
    { ru: "Я спросил, где он живет", de: "Ich habe gefragt, wo er wohnt", grammar: "В косвенном вопросе (где он живет) глагол (wohnt) уходит в конец." },
    { ru: "Она не знает, что делать", de: "Sie weiß nicht, was sie tun soll", grammar: "В придаточном предложении действие (soll) в конце." },
    { ru: "Мы работали весь день", de: "Wir haben den ganzen Tag gearbeitet", grammar: "Прошедшее время: haben ... gearbeitet." },
    { ru: "Он не пришел, потому что заболел", de: "Er ist nicht gekommen, weil er krank wurde", grammar: "После 'weil' (потому что) действие в самом конце." },
    { ru: "Я надеюсь, что все будет хорошо", de: "Ich hoffe, dass alles gut wird", grammar: "После 'dass' действие 'станет/будет' (wird) в конце." },
    { ru: "Это лучший фильм, который я видел", de: "Das ist der beste Film, den ich gesehen habe", grammar: "В описании 'который...' вспомогательный глагол (habe) ставится последним." },
    { ru: "После того как я поел, я пошел спать", de: "Nachdem ich gegessen hatte, ging ich schlafen", grammar: "Сложное время: после 'Nachdem' глагол 'hatte' в самом конце своей части." },
    { ru: "Даже если трудно, мы должны продолжать", de: "Auch wenn es schwer ist, müssen wir weitermachen", grammar: "Если предложение начинается с 'Даже если', вторая часть начинается с глагола (müssen)." },
    { ru: "Я не уверен, правильно ли это", de: "Ich bin nicht sicher, ob das richtig ist", grammar: "Слово 'ли' (ob) выгоняет глагол (ist) в конец." },
    { ru: "Он спросил меня, есть ли у меня время", de: "Er fragте mich, ob ich Zeit habe", grammar: "После 'ли' (ob) глагол 'имею' (habe) в конце." },
    { ru: "Это книга, которую я читаю", de: "Das ist das Buch, das ich lese", grammar: "Которую (das) — глагол (читаю) в конце." },
    { ru: "Завтра я буду в Берлине", de: "Morgen werde ich in Berlin sein", grammar: "Будущее время: Сначала когда (Завтра), потом стану (werde), в конце быть (sein)." },
    { ru: "Я забыл, как его зовут", de: "Ich habe vergessen, wie er heißt", grammar: "После 'как' (wie) его зовут — глагол (heißt) в конце." },
    { ru: "Она сказала, что придет позже", de: "Sie hat gesagt, dass sie später kommt", grammar: "Что (dass) выгоняет глагол в конец." },
    { ru: "Мы ждем автобус, который опаздывает", de: "Wir warten auf den Bus, der Verspätung hat", grammar: "Который (der) имеет (hat) — глагол в конце." },
    { ru: "Пока я читала, он готовил", de: "Während ich las, kochte er", grammar: "Сложный порядок: после 'Пока' (Während) действие (читала) в конце." },
    { ru: "Я позвоню тебе, как только приеду", de: "Ich rufe dich an, sobald я ankomme", grammar: "Как только (sobald) — действие (приеду/ankomme) в конце." },
    { ru: "Несмотря на дождь, мы пошли", de: "Trotz des Regens sind wir gegangen", grammar: "После предлога 'Trotz' (Несмотря на) следует падеж Genitif (кого/чего?)." },
    { ru: "Я хотел бы знать, где это", de: "Ich möchte wissen, wo das ist", grammar: "В косвенном вопросе (где это) глагол (ist) в конце." },
    { ru: "Это дом, в котором я вырос", de: "Das ist das Haus, in dem ich aufgewachsen bin", grammar: "В котором (in dem) — действие 'есть' (bin) в самом конце." },
    { ru: "Я сделал это, чтобы помочь тебе", de: "Ich habe das gemacht, um dir zu helfen", grammar: "Чтобы (um ... zu) требует инфинитив с частицей zu в самом конце." }
]);
