window.loadVocabulary("Lektion 1", [
    { word: "guten Tag!", translation: "добрый день!" },
    { word: "guten Morgen!", translation: "доброе утро!" },
    { word: "guten Abend!", translation: "добрый вечер!" },
    { word: "hallo!", translation: "привет!" },
    { word: "auf Wiedersehen!", translation: "до свидания!" },
    { word: "tschüs!", translation: "пока!" },
    { word: "gute Nacht!", translation: "спокойной ночи!" },
    { word: "Entschuldigung!", translation: "извините!" },
    { word: "bitte", translation: "пожалуйста" },
    { word: "danke", translation: "спасибо" },
    { word: "wie bitte?", translation: "что, простите?" },
    { word: "sehr angenehm", translation: "очень приятно" },
    { word: "heißen", translation: "зваться, называться" },
    { word: "arbeiten", translation: "работать" },
    { word: "bei", translation: "у, при, в (компании)" },
    { word: "leben", translation: "жить" },
    { word: "aber", translation: "но" },
    { word: "der Freund / die Freundin", translation: "друг / подруга" },
    { word: "der Student / die Studentin", translation: "студент / студентка" },
    { word: "Ich komme aus…", translation: "Я (родом) из…" },
    { word: "der Schlosser", translation: "слесарь" },
    { word: "verheiratet", translation: "женатый / замужняя" },
    { word: "mein / meine", translation: "мой / моя" },
    { word: "der Lehrer / die Lehrerin", translation: "учитель / учительница" },
    { word: "ich bin … Jahre alt", translation: "мне … лет" },
    { word: "der Schüler / die Schülerin", translation: "ученик / ученица" },
    { word: "momentan", translation: "в настоящее время" },
    { word: "die Hausfrau", translation: "домохозяйка" },
    { word: "das Kind", translation: "ребенок" },
    { word: "geschieden", translation: "разведенный" },
    { word: "an der Uni studieren", translation: "учиться в университете" },
    { word: "schlank", translation: "стройный" },
    { word: "sportlich", translation: "спортивный" },
    { word: "freundlich", translation: "дружелюбный" },
    { word: "Deutsch (Englisch) sprechen", translation: "говорить по-немецки (по-английски)" },
    { word: "natürlich", translation: "конечно" },
    { word: "zweimal pro Woche", translation: "дважды в неделю" },
    { word: "besuchen", translation: "посещать" },
    { word: "einen Spanischkurs besuchen", translation: "ходить на курсы испанского языка" },
    { word: "noch", translation: "еще" },
    { word: "in der Freizeit", translation: "в свободное время" },
    { word: "ins Kino gehen", translation: "ходить в кино" },
    { word: "ins Café gehen", translation: "ходить в кафе" },
    { word: "Klavier spielen", translation: "играть на пианино" },
    { word: "Gitarre spielen", translation: "играть на гитаре" },
    { word: "Tennis spielen", translation: "играть в теннис" },
    { word: "Fußball spielen", translation: "играть в футбол" },
    { word: "Sport machen", translation: "заниматься спортом" },
    { word: "sehr", translation: "очень" },
    { word: "am Computer sitzen", translation: "сидеть за компьютером" },
    { word: "im Internet surfen", translation: "«сидеть» в интернете" }
]);
