window.loadVocabulary("Lektion 4", [
    { word: "der Apfel", translation: "яблоко" },
    { word: "der Fisch", translation: "рыба" },
    { word: "der Kaffee", translation: "кофе" },
    { word: "der Käse", translation: "сыр" },
    { word: "der Kuchen", translation: "пирог" },
    { word: "der Saft", translation: "сок" },
    { word: "der Salat", translation: "салат" },
    { word: "der Tee", translation: "чай" },
    { word: "der Teller", translation: "тарелка" },
    { word: "der Wein", translation: "вино" },
    { word: "der Zucker", translation: "сахар" },
    { word: "das Bier", translation: "пиво" },
    { word: "das Brot", translation: "хлеб" },
    { word: "das Brötchen", translation: "булочка" },
    { word: "das Ei", translation: "яйцо" },
    { word: "das Eis", translation: "мороженое" },
    { word: "das Fleisch", translation: "мясо" },
    { word: "das Glas", translation: "стакан" },
    { word: "das Mineralwasser", translation: "минеральная вода" },
    { word: "die Banane", translation: "банан" },
    { word: "die Butter", translation: "масло" },
    { word: "die Gurke", translation: "огурец" },
    { word: "die Kartoffel", translation: "картофель" },
    { word: "die Marmelade", translation: "джем, повидло" },
    { word: "die Milch", translation: "молоко" },
    { word: "die Orange", translation: "апельсин" },
    { word: "die Suppe", translation: "суп" },
    { word: "die Tasse", translation: "чашка" },
    { word: "die Tomate", translation: "помидор" },
    { word: "die Wurst", translation: "колбаса" },
    { word: "die Zitrone", translation: "лимон" },
    { word: "essen", translation: "есть (принимать пищу)" },
    { word: "fahren", translation: "ехать" },
    { word: "fallen", translation: "падать" },
    { word: "geben", translation: "давать" },
    { word: "helfen", translation: "помогать" },
    { word: "lassen", translation: "оставлять" },
    { word: "laufen", translation: "бежать" },
    { word: "lesen", translation: "читать" },
    { word: "nehmen", translation: "брать" },
    { word: "schlafen", translation: "спать" },
    { word: "sehen", translation: "видеть" },
    { word: "sprechen", translation: "разговаривать, говорить" },
    { word: "tragen", translation: "носить" },
    { word: "treffen", translation: "встречать" },
    { word: "waschen", translation: "мыть, стирать" },
    { word: "es gibt", translation: "есть, имеется" },
    { word: "die Mahlzeit", translation: "еда, прием пищи" },
    { word: "das Frühstück", translation: "завтрак" },
    { word: "das Mittagessen", translation: "обед" },
    { word: "das Abendessen", translation: "ужин" },
    { word: "frühstücken", translation: "завтракать" },
    { word: "zu Mittag essen", translation: "обедать" },
    { word: "zu Abend essen", translation: "ужинать" },
    { word: "gewöhnlich", translation: "обычно" },
    { word: "um (8) Uhr", translation: "в (8) часов" },
    { word: "zum Frühstück", translation: "на завтрак" },
    { word: "manchmal", translation: "иногда" },
    { word: "selbst", translation: "сам" },
    { word: "die Mensa", translation: "университетская столовая" },
    { word: "das Gemüse", translation: "овощи" },
    { word: "die Nudeln", translation: "макароны, лапша" },
    { word: "lecker", translation: "вкусный" },
    { word: "der Schinken", translation: "ветчина" }
]);
