window.loadVocabulary("Lektion 12", [
    { word: "der Bus", translation: "автобус" },
    { word: "der Zug", translation: "поезд" },
    { word: "die Straßenbahn", translation: "трамвай" },
    { word: "die S-Bahn", translation: "городская электричка" },
    { word: "die U-Bahn", translation: "метро" },
    { word: "das Boot", translation: "лодка" },
    { word: "das Fahrrad", translation: "велосипед" },
    { word: "das Motorrad", translation: "мотоцикл" },
    { word: "das Schiff", translation: "корабль" },
    { word: "das Taxi", translation: "такси" },
    { word: "mit", translation: "с, на (транспорте)" },
    { word: "nach", translation: "после, в (страну/город)" },
    { word: "aus", translation: "из" },
    { word: "zu", translation: "к" },
    { word: "von", translation: "от, с" },
    { word: "bei", translation: "у" },
    { word: "seit", translation: "с (каких-либо пор)" },
    { word: "außer", translation: "кроме" },
    { word: "gegenüber", translation: "напротив" },
    { word: "nach dem Aufstehen", translation: "после подъема" },
    { word: "der Briefkasten", translation: "почтовый ящик" },
    { word: "liegen", translation: "располагаться" },
    { word: "bequem", translation: "удобный" },
    { word: "besonders", translation: "особенно" },
    { word: "checken", translation: "проверять (почту)" },
    { word: "ein bisschen", translation: "немного" }
]);
