window.loadVocabulary("Lektion 2", [
    { word: "Was ist das?", translation: "Что это?" },
    { word: "Wer ist das?", translation: "Кто это?" },
    { word: "Wo ist das?", translation: "Где это?" },
    { word: "Wann ist…?", translation: "Когда будет…?" },
    { word: "Wie geht’s?", translation: "Как дела?" },
    { word: "Wie geht es Ihnen?", translation: "Как у Вас дела?" },
    { word: "Wie heißen Sie?", translation: "Как Вас зовут?" },
    { word: "Woher kommen Sie?", translation: "Откуда Вы (родом)?" },
    { word: "Wo wohnen Sie?", translation: "Где Вы живете?" },
    { word: "Wie alt sind Sie?", translation: "Сколько Вам лет?" },
    { word: "Was sind Sie von Beruf?", translation: "Кто Вы по профессии?" },
    { word: "Wie lange arbeiten Sie bei…?", translation: "Как долго Вы работаете в…?" },
    { word: "Wie finden Sie…?", translation: "Как Вам нравится…?" },
    { word: "Was ist los?", translation: "Что случилось?" },
    { word: "Wie heißt das auf Deutsch?", translation: "Как это называется по-немецки?" },
    { word: "der Arzt / die Ärztin", translation: "врач" },
    { word: "der Buchhalter / die Buchhalterin", translation: "бухгалтер" },
    { word: "der Direktor / die Direktorin", translation: "директор" },
    { word: "der Fahrer / die Fahrerin", translation: "водитель" },
    { word: "der Geschäftsmann / die Geschäftsfrau", translation: "предприниматель" },
    { word: "der Informatiker / die Informatikerin", translation: "программист" },
    { word: "der Ingenieur / die Ingenieurin", translation: "инженер" },
    { word: "der Journalist / die Journalistin", translation: "журналист" },
    { word: "der Koch / die Köchin", translation: "повар" },
    { word: "der Mechaniker / die Mechanikerin", translation: "механик" },
    { word: "der Polizist / die Polizistin", translation: "полицейский" },
    { word: "der Sekretär / die Sekretärin", translation: "секретарь" },
    { word: "der Verkäufer / die Verkäuferin", translation: "продавец" },
    { word: "wer", translation: "кто" },
    { word: "was", translation: "что" },
    { word: "wie", translation: "как" },
    { word: "wann", translation: "когда" },
    { word: "wo", translation: "где" },
    { word: "wohin", translation: "куда" },
    { word: "woher", translation: "откуда" }
]);
