window.loadVocabulary("Lektion 3", [
    { word: "der Brief", translation: "письмо" },
    { word: "der Computer", translation: "компьютер" },
    { word: "der Koffer", translation: "чемодан" },
    { word: "der Kuli", translation: "ручка" },
    { word: "der Schlüssel", translation: "ключ" },
    { word: "der Schrank", translation: "шкаф" },
    { word: "der Stuhl", translation: "стул" },
    { word: "der Tisch", translation: "стол" },
    { word: "das Auto", translation: "автомобиль" },
    { word: "das Bett", translation: "кровать" },
    { word: "das Bild", translation: "картина" },
    { word: "das Buch", translation: "книга" },
    { word: "das Fenster", translation: "окно" },
    { word: "das Handy", translation: "сотовый телефон" },
    { word: "das Haus", translation: "дом" },
    { word: "das Sofa", translation: "диван" },
    { word: "das Zimmer", translation: "комната" },
    { word: "die Kamera", translation: "камера" },
    { word: "die Karte", translation: "карта" },
    { word: "die Lampe", translation: "лампа" },
    { word: "die Tasche", translation: "сумка" },
    { word: "die Tür", translation: "дверь" },
    { word: "die Uhr", translation: "часы" },
    { word: "die Wohnung", translation: "квартира" },
    { word: "die Zeitung", translation: "газета" },
    { word: "hell", translation: "светлый" },
    { word: "dunkel", translation: "темный" },
    { word: "gut", translation: "хороший" },
    { word: "schlecht", translation: "плохой" },
    { word: "teuer", translation: "дорогой" },
    { word: "billig", translation: "дешевый" },
    { word: "neu", translation: "новый" },
    { word: "groß", translation: "большой" },
    { word: "klein", translation: "маленький" },
    { word: "voll", translation: "полный" },
    { word: "leer", translation: "пустой" },
    { word: "mieten", translation: "снимать, арендовать" },
    { word: "gemütlich", translation: "уютный" },
    { word: "die Küche", translation: "кухня" },
    { word: "das Bad", translation: "ванная" },
    { word: "das Wohnzimmer", translation: "гостиная" },
    { word: "der Sessel", translation: "кресло" },
    { word: "modern", translation: "современный" },
    { word: "das Schlafzimmer", translation: "спальня" },
    { word: "ziemlich", translation: "довольно, достаточно" },
    { word: "der Herd", translation: "плита" },
    { word: "der Kühlschrank", translation: "холодильник" },
    { word: "die Badewanne", translation: "ванна" },
    { word: "die Dusche", translation: "душ" },
    { word: "die Toilette", translation: "туалет" },
    { word: "die Waschmaschine", translation: "стиральная машина" },
    { word: "kosten", translation: "стоить" },
    { word: "der Monat", translation: "месяц" }
]);
