window.loadVocabulary("Lektion 5", [
    { word: "der Ausgang", translation: "выход" },
    { word: "der Eingang", translation: "вход" },
    { word: "der Käufer", translation: "покупатель" },
    { word: "der Preis", translation: "цена" },
    { word: "der Supermarkt", translation: "супермаркет" },
    { word: "der Verkäufer", translation: "продавец" },
    { word: "das Angebot", translation: "специальное предложение" },
    { word: "das Getränk", translation: "напиток" },
    { word: "das Regal", translation: "стеллаж, полка" },
    { word: "das Geld", translation: "деньги" },
    { word: "die Kasse", translation: "касса" },
    { word: "die Tüte", translation: "пакет" },
    { word: "die Ware", translation: "товар" },
    { word: "der Liter", translation: "литр" },
    { word: "das Glas", translation: "банка (стеклянная)" },
    { word: "das Kilo", translation: "килограмм" },
    { word: "das Netz", translation: "сетка (овощей, фруктов)" },
    { word: "das Stück", translation: "кусок" },
    { word: "die Dose", translation: "банка (металлическая)" },
    { word: "die Flasche", translation: "бутылка" },
    { word: "die Packung", translation: "упаковка, пачка" },
    { word: "wieder", translation: "опять, снова" },
    { word: "die Lebensmittel", translation: "продукты (питания)" },
    { word: "die Liste", translation: "список" },
    { word: "vergessen", translation: "забывать" },
    { word: "das Obst", translation: "фрукты" },
    { word: "dann", translation: "потом, тогда" },
    { word: "wiegen", translation: "взвешивать" },
    { word: "die Sorte", translation: "сорт" },
    { word: "zum Schluss", translation: "напоследок" },
    { word: "bezahlen", translation: "оплачивать" },
    { word: "packen", translation: "паковать" }
]);
