window.loadVocabulary("Lektion 9", [
    { word: "der Bleistift", translation: "карандаш" },
    { word: "der Fehler", translation: "ошибка" },
    { word: "der Satz", translation: "предложение" },
    { word: "der Unterricht", translation: "занятие, занятия" },
    { word: "die Antwort", translation: "ответ" },
    { word: "die Aufgabe", translation: "задание" },
    { word: "die Frage", translation: "вопрос" },
    { word: "die Fremdsprache", translation: "иностранный язык" },
    { word: "die Grammatik", translation: "грамматика" },
    { word: "die Gruppe", translation: "группа" },
    { word: "die Hausaufgabe", translation: "домашнее задание" },
    { word: "die Note", translation: "оценка" },
    { word: "die Pause", translation: "перемена" },
    { word: "die Prüfung", translation: "экзамен" },
    { word: "die Regel", translation: "правило" },
    { word: "die Seite", translation: "страница" },
    { word: "die Sprache", translation: "язык" },
    { word: "die Tafel", translation: "доска" },
    { word: "die Übung", translation: "упражнение" },
    { word: "das Beispiel", translation: "пример, образец" },
    { word: "das Heft", translation: "тетрадь" },
    { word: "das Lehrbuch", translation: "учебник" },
    { word: "das Thema", translation: "тема" },
    { word: "das Wort", translation: "слово" },
    { word: "das Wörterbuch", translation: "словарь" },
    { word: "können", translation: "мочь, уметь" },
    { word: "bestehen aus", translation: "состоять из" },
    { word: "fehlen", translation: "отсутствовать" },
    { word: "Platz nehmen", translation: "садиться" },
    { word: "zuerst", translation: "сначала" },
    { word: "prüfen", translation: "проверять" },
    { word: "korrigieren", translation: "исправлять" },
    { word: "erklären", translation: "объяснять" },
    { word: "wiederholen", translation: "повторять" },
    { word: "mündlich", translation: "устно" },
    { word: "schriftlich", translation: "письменно" },
    { word: "Was bedeutet…?", translation: "Что означает…?" },
    { word: "alles ist klar", translation: "все понятно" },
    { word: "bekommen", translation: "получать" },
    { word: "dauern", translation: "длиться" },
    { word: "die Stunde", translation: "час (60 минут)" },
    { word: "enden", translation: "заканчиваться" }
]);
