window.loadVocabulary("Lektion 8", [
    { word: "der Bruder", translation: "брат" },
    { word: "der Enkel", translation: "внук" },
    { word: "der Großvater", translation: "дедушка" },
    { word: "der Junge", translation: "мальчик" },
    { word: "der Mann", translation: "мужчина, муж" },
    { word: "der Mensch", translation: "человек" },
    { word: "der Onkel", translation: "дядя" },
    { word: "der Sohn", translation: "сын" },
    { word: "der Vater", translation: "отец" },
    { word: "die Enkelin", translation: "внучка" },
    { word: "die Familie", translation: "семья" },
    { word: "die Frau", translation: "женщина, жена" },
    { word: "die Großmutter", translation: "бабушка" },
    { word: "die Mutter", translation: "мать" },
    { word: "die Schwester", translation: "сестра" },
    { word: "die Tante", translation: "тетя" },
    { word: "die Tochter", translation: "дочь" },
    { word: "das Kind", translation: "ребенок" },
    { word: "das Mädchen", translation: "девочка, девушка" },
    { word: "die Eltern", translation: "родители" },
    { word: "die Geschwister", translation: "братья и сестры" },
    { word: "die Großeltern", translation: "бабушка и дедушка" },
    { word: "die Verwandten", translation: "родственники" },
    { word: "leider", translation: "к сожалению" },
    { word: "ist tot", translation: "умер(ла)" },
    { word: "der Rentner / die Rentnerin", translation: "пенсионер / пенсионерка" },
    { word: "den Haushalt führen", translation: "вести домашнее хозяйство" },
    { word: "der Kindergarten", translation: "детский сад" },
    { word: "immer", translation: "всегда" },
    { word: "Weihnachten", translation: "Рождество" },
    { word: "feiern", translation: "праздновать" }
]);
