window.loadVocabulary("Lektion 0", [
    { word: "Präsident", translation: "президент" },
    { word: "Fakultät", translation: "факультет" },
    { word: "Köln", translation: "Кёльн" },
    { word: "München", translation: "Мюнхен" },
    { word: "Maja", translation: "Майя" },
    { word: "ja", translation: "да" },
    { word: "jetzt", translation: "сейчас" },
    { word: "Ball", translation: "мяч" },
    { word: "alt", translation: "старый" },
    { word: "Rolle", translation: "роль" },
    { word: "Frau", translation: "женщина, госпожа" },
    { word: "Mutter", translation: "мать" },
    { word: "Bruder", translation: "брат" },
    { word: "Wagen", translation: "автомобиль" },
    { word: "was", translation: "что" },
    { word: "Zimmer", translation: "комната" },
    { word: "tanzen", translation: "танцевать" },
    { word: "Bus", translation: "автобус" },
    { word: "Maus", translation: "мышь" },
    { word: "Saft", translation: "сок" },
    { word: "Hose", translation: "брюки" },
    { word: "Fuß", translation: "нога (стопа)" },
    { word: "süß", translation: "сладкий" },
    { word: "mein", translation: "мой" },
    { word: "Wein", translation: "вино" },
    { word: "Polizei", translation: "полиция" },
    { word: "Europa", translation: "Европа" },
    { word: "Euro", translation: "евро" },
    { word: "Freund", translation: "друг" },
    { word: "Deutsch", translation: "немецкий язык" },
    { word: "Löwenbräu", translation: "Лёвенброй (марка пива)" },
    { word: "Schule", translation: "школа" },
    { word: "Dusche", translation: "душ" },
    { word: "machen", translation: "делать" },
    { word: "Koch", translation: "повар" },
    { word: "Buch", translation: "книга" },
    { word: "Technik", translation: "техника" },
    { word: "ich", translation: "я" },
    { word: "Mädchen", translation: "девочка" },
    { word: "Bahn", translation: "дорога, путь" },
    { word: "wohnen", translation: "жить (где-либо)" },
    { word: "Schuh", translation: "ботинок" },
    { word: "gehen", translation: "идти" },
    { word: "Biene", translation: "пчела" },
    { word: "lieben", translation: "любить" },
    { word: "sie", translation: "она, они, Вы" },
    { word: "Student", translation: "студент" },
    { word: "Sport", translation: "спорт" },
    { word: "ledig", translation: "холостой, незамужняя" },
    { word: "Leipzig", translation: "Лейпциг" },
    { word: "König", translation: "король" }
]);
