window.loadVocabulary("Lektion 6", [
    { word: "der Handschuh", translation: "перчатка" },
    { word: "der Mantel", translation: "пальто" },
    { word: "der Pullover", translation: "пуловер, джемпер" },
    { word: "der Rock", translation: "юбка" },
    { word: "der Schal", translation: "шарф" },
    { word: "der Schuh", translation: "ботинок, туфля" },
    { word: "das Hemd", translation: "рубашка" },
    { word: "das Kleid", translation: "платье" },
    { word: "das T-Shirt", translation: "футболка" },
    { word: "die Bluse", translation: "блузка" },
    { word: "die Hose", translation: "брюки" },
    { word: "die Jacke", translation: "куртка" },
    { word: "die Kleidung", translation: "одежда" },
    { word: "die Mütze", translation: "шапка" },
    { word: "die Socke", translation: "носок" },
    { word: "schwer", translation: "тяжелый" },
    { word: "leicht", translation: "легкий" },
    { word: "lang", translation: "длинный" },
    { word: "kurz", translation: "короткий" },
    { word: "schön", translation: "красивый" },
    { word: "hässlich", translation: "некрасивый" },
    { word: "dick", translation: "толстый" },
    { word: "dünn", translation: "тонкий" },
    { word: "modisch", translation: "модный" },
    { word: "praktisch", translation: "практичный" },
    { word: "bequem", translation: "удобный" },
    { word: "blau", translation: "синий, голубой" },
    { word: "braun", translation: "коричневый" },
    { word: "gelb", translation: "желтый" },
    { word: "grau", translation: "серый" },
    { word: "grün", translation: "зеленый" },
    { word: "rot", translation: "красный" },
    { word: "schwarz", translation: "черный" },
    { word: "weiß", translation: "белый" },
    { word: "ein paar", translation: "несколько" },
    { word: "die Jahreszeit", translation: "время года" },
    { word: "der Winter (im Winter)", translation: "зима (зимой)" },
    { word: "der Sommer (im Sommer)", translation: "лето (летом)" },
    { word: "der Herbst (im Herbst)", translation: "осень (осенью)" },
    { word: "der Frühling (im Frühling)", translation: "весна (весной)" },
    { word: "kühl", translation: "прохладный" },
    { word: "zu", translation: "слишком" },
    { word: "die Markenkleidung", translation: "«брендовая» одежда" },
    { word: "schick", translation: "нарядный, изящный" },
    { word: "das Geschenk", translation: "подарок" }
]);
