window.loadVocabulary("Lektion 10", [
    { word: "der Hunger", translation: "голод" },
    { word: "der Kellner", translation: "официант" },
    { word: "der Löffel", translation: "ложка" },
    { word: "der Senf", translation: "горчица" },
    { word: "die Gabel", translation: "вилка" },
    { word: "die Nachspeise", translation: "десерт" },
    { word: "die Rechnung", translation: "счет" },
    { word: "die Serviette", translation: "салфетка" },
    { word: "die Soße", translation: "соус" },
    { word: "die Speise", translation: "блюдо" },
    { word: "die Speisekarte", translation: "меню" },
    { word: "die Vorspeise", translation: "закуска" },
    { word: "das Getränk", translation: "напиток" },
    { word: "das Messer", translation: "нож" },
    { word: "das Salz", translation: "соль" },
    { word: "das Trinkgeld", translation: "чаевые" },
    { word: "bestellen", translation: "заказывать" },
    { word: "wünschen", translation: "желать" },
    { word: "rufen", translation: "звать" },
    { word: "zahlen", translation: "платить" },
    { word: "Stimmt so!", translation: "Сдачи не надо!" },
    { word: "danken für", translation: "благодарить за" },
    { word: "mögen", translation: "любить (продукты, хобби)" }
]);
